config/routes.rb
AseSe::Application.routes.draw do
  resources :server_events

end

app/models/server_event.rb
class ServerEvent < ActiveRecord::Base

 #self.per_page = 20

  before_save {|e|
    logger.info 'in before_save of ServerEvent '+e.inspect
    e.vakz = 'initial' if e.vakz.blank?
    e.va1kz = 'initial' if e.va1kz.blank?
  }

  attr_accessible :name, :vakz, :va1kz

  scope :by_name, :order => :name

end

#
# vim: fdm=syntax
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  WillPaginate.per_page=45

end

app/controllers/server_events_controller.rb
class ServerEventsController < ApplicationController

  before_filter do
    #session[:page] ||= params[:page] unless params[:page] != session[:page]
    #session[:page] = params[:page] if params[:page] && params[:page] != session[:page]

    session[:page] = params[:page] if params[:page]
    session[:page]||=1

    ### stoert update
    #if session[:page] != params[:page]
    #  redirect_to :controller => controller_name, :action => action_name, page: session[:page], :params=> params and return
    #end

    #if   params[:controller].blank? || params[:action].blank?
    #  redirect_to :controller => controller_name, :action => action_name, page: session[:page], :params=> params and return
    #end

    #if params[:sane].blank?
    #  redirect_to :controller => :server_events, :action => action_name, page: session[:page], :params=> params, :sane=>:true and return
    #end
  end

  # GET /server_events
  # GET /server_events.json
  def index
    @server_events =
        ServerEvent.by_name.paginate :page => session[:page]
    #ServerEvent.by_name.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @server_events }
    end
  end

  # GET /server_events/1
  # GET /server_events/1.json
  def show
    @server_event = ServerEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server_event }
    end
  end

  # GET /server_events/new
  # GET /server_events/new.json
  def new
    @server_event = ServerEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server_event }
    end
  end

  # GET /server_events/1/edit
  def edit
    @server_event = ServerEvent.find(params[:id])
  end

  # POST /server_events
  # POST /server_events.json
  def create
    @server_event = ServerEvent.new(params[:server_event])

    respond_to do |format|
      if @server_event.save
        format.html { redirect_to @server_event, notice: 'Server event was successfully created.' }
        format.json { render json: @server_event, status: :created, location: @server_event }
      else
        format.html { render action: "new" }
        format.json { render json: @server_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /server_events/1
  # PUT /server_events/1.json
  def update
    @server_event = ServerEvent.find(params[:id])

    respond_to do |format|
      if @server_event.update_attributes(params[:server_event])
        format.html { redirect_to @server_event, notice: 'Server event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", notice: 'Server event was not updated!' }
        format.json { render json: @server_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /server_events/1
  # DELETE /server_events/1.json
  def destroy
    @server_event = ServerEvent.find(params[:id])
    @server_event.destroy

    respond_to do |format|
      format.html { redirect_to server_events_url }
      format.json { head :no_content }
    end
  end
end

#
# vim: fdm=syntax
#

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/server_events_helper.rb
module ServerEventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AseSe</title>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%#= stylesheet_link_tag    'screen', :media => 'screen,projection' %>
  <%= stylesheet_link_tag 'http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
  <div class="static">
    <%= yield :static %>
    <div class="header">
      <%= yield :header %>
    </div>
    <div class="menu">
      <%= yield :menu %>
    </div>
  </div>
  <div class="content">
    <%= yield :content %>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/server_events/_form.html.erb
<%= form_for(@server_event) do |f| %>
  <% if @server_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server_event.errors.count, "error") %> prohibited this server_event from being saved:</h2>

      <ul>
      <% @server_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :vakz %><br />
    <%= f.text_field :vakz %>
  </div>
  <div class="field">
    <%= f.label :va1kz %><br />
    <%= f.text_field :va1kz %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/server_events/edit.html.erb
<%= content_for :header do %>
    <h1>Editing server_event</h1>
<% end %>
<div class='grid_12' style='background-color: aquamarine;'>
<%= render 'form' %>
</div>
<%= content_for :menu do %>
    <div>
    <%= link_to 'Show', @server_event %> |
    <%= link_to 'Back', server_events_path %>
    </div>
<% end %>

app/views/server_events/index.html.erb
<%= content_for :header do %>
    <h1>Listing server_events</h1>
<% end %>
<%= content_for :menu do %>
    <%= will_paginate @server_events,
                      renderer: BootstrapPagination::Rails,
                      class: 'pagination-centered' %>
    <p><%= link_to 'New Server event', new_server_event_path %></p>
<% end %>

<div class='r-listing'>
  <table>
    <tr>
      <th>Name</th>
      <th>Vakz</th>
      <th>Va1kz</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>


    <% @server_events.each do |server_event| %>
        <tr>
          <td><%= server_event.name %></td>
          <td><%= server_event.vakz %></td>
          <td><%= server_event.va1kz %></td>
          <td><%= link_to 'Show', server_event %></td>
          <td><%= link_to 'Edit', edit_server_event_path(server_event) %></td>
          <td><%= link_to 'Destroy', server_event, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
  </table>
</div>

app/views/server_events/new.html.erb
<%= content_for :header do %>
    <h1>New server_event</h1>
<% end %>
<div>
  <%= render 'form' %>
</div>
<%= content_for :menu do %>
    <div>
      <%= link_to 'Back', server_events_path %>
    </div>
<% end %>

app/views/server_events/show.html.erb
<%= content_for :header do %>
    <h1>Server Event</h1>
<% end %>
<%= content_for :menu do %>
    <div>
      <%= link_to 'Edit', edit_server_event_path(@server_event) %> |
      <%= link_to 'Back', server_events_path %>
    </div>
<% end %>
<%= content_for :content do %>
    <p id="notice"><%= notice %></p>
<% end %>
<div>
  <h4>
    <b>Name:</b>
    <%= @server_event.name %>
  </h4>

  <p>
    <b>Vakz:</b>
    <%= @server_event.vakz %>
  </p>

  <p>
    <b>Va1kz:</b>
    <%= @server_event.va1kz %>
  </p>
</div>